# Form implementation generated from reading ui file 'voting_system.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_voting_system(object):
    def setupUi(self, voting_system):
        voting_system.setObjectName("voting_system")
        voting_system.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=voting_system)
        self.centralwidget.setObjectName("centralwidget")
        self.first_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.first_name.setGeometry(QtCore.QRect(250, 60, 113, 22))
        self.first_name.setObjectName("first_name")
        self.last_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.last_name.setGeometry(QtCore.QRect(250, 90, 113, 22))
        self.last_name.setObjectName("last_name")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 60, 81, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(154, 80, 81, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(380, 80, 55, 16))
        self.label_3.setObjectName("label_3")
        self.i_d = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.i_d.setGeometry(QtCore.QRect(400, 80, 113, 22))
        self.i_d.setObjectName("i_d")
        self.voting_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.voting_label.setGeometry(QtCore.QRect(330, 10, 141, 20))
        self.voting_label.setObjectName("voting_label")
        self.cand_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.cand_label.setGeometry(QtCore.QRect(250, 140, 71, 16))
        self.cand_label.setObjectName("cand_label")
        self.thomas_j = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.thomas_j.setGeometry(QtCore.QRect(280, 170, 131, 20))
        self.thomas_j.setObjectName("thomas_j")
        self.george_w = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.george_w.setGeometry(QtCore.QRect(280, 200, 141, 20))
        self.george_w.setObjectName("george_w")
        self.abraham_l = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.abraham_l.setGeometry(QtCore.QRect(280, 230, 131, 20))
        self.abraham_l.setObjectName("abraham_l")
        self.vote_submit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.vote_submit.setGeometry(QtCore.QRect(300, 270, 93, 28))
        self.vote_submit.setObjectName("vote_submit")
        self.login_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.login_button.setGeometry(QtCore.QRect(540, 70, 93, 28))
        self.login_button.setObjectName("login_button")
        self.exit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(410, 270, 93, 28))
        self.exit_button.setObjectName("pushButton")
        voting_system.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=voting_system)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        voting_system.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=voting_system)
        self.statusbar.setObjectName("statusbar")
        voting_system.setStatusBar(self.statusbar)

        self.retranslateUi(voting_system)
        QtCore.QMetaObject.connectSlotsByName(voting_system)

    def retranslateUi(self, voting_system):
        _translate = QtCore.QCoreApplication.translate
        voting_system.setWindowTitle(_translate("voting_system", "Voting System"))
        self.label.setText(_translate("voting_system", "FIRST NAME"))
        self.label_2.setText(_translate("voting_system", "LAST NAME"))
        self.label_3.setText(_translate("voting_system", "ID"))
        self.voting_label.setText(_translate("voting_system", "VOTING REGISTRATION"))
        self.cand_label.setText(_translate("voting_system", "CANIDATES"))
        self.thomas_j.setText(_translate("voting_system", "Thomas Jefferson"))
        self.george_w.setText(_translate("voting_system", "George Washington"))
        self.abraham_l.setText(_translate("voting_system", "Abraham Lincoln"))
        self.vote_submit.setText(_translate("voting_system", "VOTE"))
        self.login_button.setText(_translate("voting_system", "LOG IN"))
        self.exit_button.setText(_translate("voting_system", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    voting_system = QtWidgets.QMainWindow()
    ui = Ui_voting_system()
    ui.setupUi(voting_system)
    voting_system.show()
    sys.exit(app.exec())
